apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: default
  labels:
    component: nats
spec:
  selector:
    component: nats
  type: ClusterIP
  ports:
    - name: client
      port: 4222
    - name: cluster
      port: 6222
    - name: monitor
      port: 8222
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    component: nats
  name: nats
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: nats
  serviceName: nats
  template:
    metadata:
      labels:
        component: nats
    spec:
      containers:
        - image: nats:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8222
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: nats
          ports:
            - containerPort: 4222
              name: client
              protocol: TCP
            - containerPort: 6222
              name: cluster
              protocol: TCP
            - containerPort: 8222
              name: monitor
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  updateStrategy:
    type: OnDelete
status:
  availableReplicas: 2
  replicas: 2
